### Exploring Factors Affecting Team Performance in the NBA

<a target="_blank" href="https://colab.research.google.com/github/nayakhayat/is310-coding-assignments/blob/main/NBA%20Project.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

_Introduction_ <br>
In my final project, I decided to analyze the relationship between team performance in the NBA and various factors such as total points per game (PPG) and social media engagement, which was measured by Facebook likes. The motivation behind this study comes from the desire to understand the complex intersection of factors that contribute to a team's success in the NBA.

Relating to the topic of my project, the systematic scoping review titled "Factors Influencing Team Performance: What Can Support Teams in High-Performance Sport Learn from Other Industries?" by Salcinovic et al. provides valuable insights into the factors influencing team function and performance. This paper aligns closely with the purpose of my project, which aims to explore factors influencing team performance in the NBA, specifically looking at correlations between performance metrics and other potential influencing factors.

The review identifies four key variables associated with team function and performance across different sectors: leadership styles, supportive team behavior, communication, and performance feedback. These variables are crucial components of effective teamwork and can potentially impact team performance in basketball as well. 

For this project, I was able to utilize the findings of this review to broaden my understanding of the factors that may contribute to team success beyond traditional performance metrics like points per game and number of wins. For example, after looking at any correlations found between PPG or social media engagement, I can further analyze how different leadership styles among coaches or team captains influence team dynamics and performance. Additionally, I could investigate the role of supportive team behavior in creating a positive team culture and its impact on the performance of a team.

Overall, this systematic scoping review offers valuable insights and other potential approaches for further exploration in my project, allowing me to better understand the nature of team performance in basketball and identify additional factors that may influence team success.

_Data Collection & Curation_ <br>The data collection process involved gathering information on total PPG (based on all players from each team) and number of wins, along with data on Facebook likes for each team, which gave me an insight on each team’s social media/fan engagement. These datasets were sourced from statistics sources, including NBAStuffer and Statista. To ensure consistency and accuracy, data cleaning techniques were applied to match team names across datasets, and to ensure that all columns were named correctly. Other methods of data curation involved addressing inconsistencies and missing values in the datasets. Manual data cleaning and computational methods, such as imputation, were used to enhance the data and create dataframes with only the necessary data. The final dataset was structured to make analysis and interpretation easier and more efficient.

_Data Analysis & Methods_ <br>The analysis aspect first focused on exploring the relationship between total PPG per team and number of wins. Statistical techniques such as correlation analysis and data visualization were used to assess the strength and significance of this relationship. Visualizations, including Altair scatter plots, were used to illustrate any correlations and trends in the data.

Furthermore, qualitative analysis techniques were applied to the facebook likes data to gain more insights into team popularity and fan engagement. From this, I was able to gain valuable context relating to the quantitative findings, which helped me gain a better understanding of the factors influencing team performance after looking at the first correlation.

_Conclusion & Reflection_ <br>The findings of this study revealed no significant correlation between total PPG and number of wins, suggesting that scoring more points does not necessarily affect the amount of victories for a team in the NBA. After discovering this, and wanting to look at another potential factor  in influencing team performance, I looked at the relationship between facebook likes for each team and their number of wins. Similarly, I found that social media engagement was also not a reliable predictor of team success.

These results highlight the multifaceted nature of team performance in the NBA, showing that factors beyond on court performance and social media presence influence a team’s success. Team environments, player cohesion, coaching strategies, and other factors such as injuries and schedule constraints could all play key roles in determining success.

Moving forward, future research could explore these additional factors and look at metrics such as player demographics, fan demographics, and market dynamics, to gain a more comprehensive understanding of team performance. Additionally, other studies examining fan behavior and team environments could provide valuable insights into the complex relationship between the NBA fandom and team success.

_References_ <br> Salcinovic, B., Drew, M., Dijkstra, P., Waddington, G., & Serpell, B. G. (2022). Factors influencing team performance: What can support teams in high-performance sport learn from other industries? A systematic scoping review. Sports Medicine - Open, 8(1). https://doi.org/10.1186/s40798-021-00406-7 <br>NBA Team Advanced stats: Away/home/last 5 splits. NBAstuffer. (n.d.). https://www.nbastuffer.com/nba-stats/team/ <br>18, O. (2023, October 18). NBA teams’ Facebook likes 2023. Statista. https://www.statista.com/statistics/240382/facebook-fans-of-national-basketball-association-teams/

### Code:

In [394]:
import pandas as pd
import matplotlib.pyplot as plt

In [395]:
df = pd.read_csv("NBA Stats 202324 All Stats  NBA Player Props Tool.csv")

In [396]:
df

,RANK,NAME,TEAM,POS,AGE,GP,MPG,USG%,TO%,FTA,...,APG,SPG,BPG,TPG,P+R,P+A,P+R+A,VI,ORtg,DRtg
0,NaN,Joel Embiid,Phi,C,30.0,34,34.0,39.0,14.3,403,...,5.7,1.1,1.8,3.7,46.6,41.0,52.3,15.5,125.6,106.4
1,NaN,Luka Doncic,Dal,G,25.0,53,37.5,36.0,14.2,486,...,9.7,1.5,0.6,3.9,43.5,44.3,53.2,15.3,123.7,112.1
2,NaN,Shai Gilgeous-Alexander,Okc,G,25.6,60,34.4,32.9,9.7,533,...,6.5,2.2,1.0,2.2,36.7,37.6,43.2,12.1,131.3,107.9
3,NaN,Giannis Antetokounmpo,Mil,F,29.2,59,34.9,32.9,15.4,651,...,6.3,1.3,1.0,3.4,42.1,37.1,48.4,14.9,127.0,106.3
4,NaN,Donovan Mitchell,Cle,G,27.5,47,35.7,31.8,12.5,287,...,6.2,1.8,0.5,2.9,33.4,34.1,39.6,11.0,119.1,107.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,NaN,Justin Jackson,Min,F,28.9,2,0.4,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
614,NaN,Pat Spencer,Gol,G,27.7,1,1.8,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
615,NaN,Jalen Crutcher,Nor,G,24.6,1,2.7,15.9,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
616,NaN,Marques Bolden,Cha,C,25.9,2,6.3,6.9,50.0,0,...,0.0,0.0,0.0,0.5,0.5,0.0,0.5,0.0,0.0,118.6
617,NaN,Harry Giles III,Lal,F-C,25.9,1,3.6,12.0,0.0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [397]:
df.isna().sum()

RANK     618
NAME       0
TEAM       0
POS        0
AGE        0
GP         0
MPG        0
USG%       0
TO%        0
FTA        0
FT%        0
2PA        0
2P%        0
3PA        0
3P%        0
eFG%       0
TS%        0
PPG        0
RPG        0
APG        0
SPG        0
BPG        0
TPG        0
P+R        0
P+A        0
P+R+A      0
VI         0
ORtg       0
DRtg       0
dtype: int64

In [398]:
df.drop('RANK', axis=1)

,NAME,TEAM,POS,AGE,GP,MPG,USG%,TO%,FTA,FT%,...,APG,SPG,BPG,TPG,P+R,P+A,P+R+A,VI,ORtg,DRtg
0,Joel Embiid,Phi,C,30.0,34,34.0,39.0,14.3,403,0.883,...,5.7,1.1,1.8,3.7,46.6,41.0,52.3,15.5,125.6,106.4
1,Luka Doncic,Dal,G,25.0,53,37.5,36.0,14.2,486,0.784,...,9.7,1.5,0.6,3.9,43.5,44.3,53.2,15.3,123.7,112.1
2,Shai Gilgeous-Alexander,Okc,G,25.6,60,34.4,32.9,9.7,533,0.882,...,6.5,2.2,1.0,2.2,36.7,37.6,43.2,12.1,131.3,107.9
3,Giannis Antetokounmpo,Mil,F,29.2,59,34.9,32.9,15.4,651,0.661,...,6.3,1.3,1.0,3.4,42.1,37.1,48.4,14.9,127.0,106.3
4,Donovan Mitchell,Cle,G,27.5,47,35.7,31.8,12.5,287,0.864,...,6.2,1.8,0.5,2.9,33.4,34.1,39.6,11.0,119.1,107.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,Justin Jackson,Min,F,28.9,2,0.4,0.0,0.0,0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
614,Pat Spencer,Gol,G,27.7,1,1.8,0.0,0.0,0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
615,Jalen Crutcher,Nor,G,24.6,1,2.7,15.9,0.0,0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
616,Marques Bolden,Cha,C,25.9,2,6.3,6.9,50.0,0,0.000,...,0.0,0.0,0.0,0.5,0.5,0.0,0.5,0.0,0.0,118.6
617,Harry Giles III,Lal,F-C,25.9,1,3.6,12.0,0.0,0,0.000,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [399]:
df = df.assign(RANK=range(len(df)))
df

,RANK,NAME,TEAM,POS,AGE,GP,MPG,USG%,TO%,FTA,...,APG,SPG,BPG,TPG,P+R,P+A,P+R+A,VI,ORtg,DRtg
0,0,Joel Embiid,Phi,C,30.0,34,34.0,39.0,14.3,403,...,5.7,1.1,1.8,3.7,46.6,41.0,52.3,15.5,125.6,106.4
1,1,Luka Doncic,Dal,G,25.0,53,37.5,36.0,14.2,486,...,9.7,1.5,0.6,3.9,43.5,44.3,53.2,15.3,123.7,112.1
2,2,Shai Gilgeous-Alexander,Okc,G,25.6,60,34.4,32.9,9.7,533,...,6.5,2.2,1.0,2.2,36.7,37.6,43.2,12.1,131.3,107.9
3,3,Giannis Antetokounmpo,Mil,F,29.2,59,34.9,32.9,15.4,651,...,6.3,1.3,1.0,3.4,42.1,37.1,48.4,14.9,127.0,106.3
4,4,Donovan Mitchell,Cle,G,27.5,47,35.7,31.8,12.5,287,...,6.2,1.8,0.5,2.9,33.4,34.1,39.6,11.0,119.1,107.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,613,Justin Jackson,Min,F,28.9,2,0.4,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
614,614,Pat Spencer,Gol,G,27.7,1,1.8,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
615,615,Jalen Crutcher,Nor,G,24.6,1,2.7,15.9,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
616,616,Marques Bolden,Cha,C,25.9,2,6.3,6.9,50.0,0,...,0.0,0.0,0.0,0.5,0.5,0.0,0.5,0.0,0.0,118.6
617,617,Harry Giles III,Lal,F-C,25.9,1,3.6,12.0,0.0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [400]:
filtered_df = df[['NAME','RANK', 'TEAM', 'PPG', 'APG', 'RPG', 'eFG%', '3P%', 'FT%', 'TPG']]
filtered_df

,NAME,RANK,TEAM,PPG,APG,RPG,eFG%,3P%,FT%,TPG
0,Joel Embiid,0,Phi,35.3,5.7,11.3,0.560,0.366,0.883,3.7
1,Luka Doncic,1,Dal,34.5,9.7,8.9,0.578,0.380,0.784,3.9
2,Shai Gilgeous-Alexander,2,Okc,31.1,6.5,5.6,0.578,0.383,0.882,2.2
3,Giannis Antetokounmpo,3,Mil,30.8,6.3,11.3,0.633,0.301,0.661,3.4
4,Donovan Mitchell,4,Cle,28.0,6.2,5.4,0.555,0.371,0.864,2.9
...,...,...,...,...,...,...,...,...,...,...
613,Justin Jackson,613,Min,0.0,0.0,0.0,0.000,0.000,0.000,0.0
614,Pat Spencer,614,Gol,0.0,0.0,0.0,0.000,0.000,0.000,0.0
615,Jalen Crutcher,615,Nor,0.0,0.0,0.0,0.000,0.000,0.000,0.0
616,Marques Bolden,616,Cha,0.0,0.0,0.5,0.000,0.000,0.000,0.5
617,Harry Giles III,617,Lal,0.0,0.0,1.0,0.000,0.000,0.000,0.0

In [401]:
filtered_df.head(15)

,NAME,RANK,TEAM,PPG,APG,RPG,eFG%,3P%,FT%,TPG
0,Joel Embiid,0,Phi,35.3,5.7,11.3,0.560,0.366,0.883,3.7
1,Luka Doncic,1,Dal,34.5,9.7,8.9,0.578,0.380,0.784,3.9
2,Shai Gilgeous-Alexander,2,Okc,31.1,6.5,5.6,0.578,0.383,0.882,2.2
3,Giannis Antetokounmpo,3,Mil,30.8,6.3,11.3,0.633,0.301,0.661,3.4
4,Donovan Mitchell,4,Cle,28.0,6.2,5.4,0.555,0.371,0.864,2.9
5,Kevin Durant,5,Pho,27.8,5.5,6.7,0.585,0.421,0.856,3.3
6,Devin Booker,6,Pho,27.5,6.8,4.6,0.551,0.379,0.880,2.6
7,Jalen Brunson,7,Nyk,27.2,6.6,3.7,0.542,0.407,0.846,2.5
8,Stephen Curry,8,Gol,27.1,5.0,4.3,0.575,0.407,0.922,3.0
9,Jayson Tatum,9,Bos,27.1,4.8,8.4,0.558,0.369,0.829,2.5
10,De'Aaron Fox,10,Sac,26.8,5.7,4.2,0.540,0.368,0.709,2.7
11,Trae Young,11,Atl,26.4,10.8,2.7,0.512,0.371,0.856,4.3
12,Anthony Edwards,12,Min,26.1,5.1,5.2,0.530,0.378,0.842,3.2
13,Tyrese Maxey,13,Phi,26.0,6.3,3.7,0.524,0.378,0.871,1.7
14,Nikola Jokic,14,Den,25.9,9.2,12.3,0.610,0.341,0.820,2.9

In [402]:
df2 = pd.read_csv("NBA Stats 202324 Team Metrics Away-Home-Last 5 Splits.csv")

In [403]:
df2

,RANK,TEAM,CONF,DIVISION,GP,PPG,oPPG,pDIFF,PACE,oEFF,...,SAR,CONS,A4F,W,L,WIN%,eWIN%,pWIN%,ACH,STRK
0,NaN,Boston,East,Atlantic,60,121.3,109.9,11.4,98.0,122.8,...,11.18,16.6,0.096,48,12,0.800,0.758,0.875,0.042,11
1,NaN,Milwaukee,East,Central,62,121.4,116.9,4.5,100.7,119.9,...,3.29,15.6,0.059,41,21,0.661,0.611,0.648,0.050,6
2,NaN,Cleveland,East,Central,60,114.4,109.5,4.9,97.7,116.2,...,3.95,14.3,0.050,39,21,0.650,0.635,0.661,0.015,-1
3,NaN,New York,East,Atlantic,61,113.4,109.7,3.7,96.0,118.2,...,3.68,15.8,-0.003,36,25,0.590,0.597,0.622,-0.007,1
4,NaN,Philadelphia,East,Atlantic,60,117.1,113.8,3.3,98.4,118.6,...,1.70,17.1,-0.043,35,25,0.583,0.579,0.609,0.004,2
5,NaN,Orlando,East,Southeast,61,111.5,109.9,1.6,97.5,113.6,...,2.21,14.9,0.002,35,26,0.574,0.543,0.553,0.031,3
6,NaN,Miami,East,Southeast,60,110.6,109.9,0.7,96.8,114.2,...,0.42,13.1,-0.029,34,26,0.567,0.524,0.523,0.043,1
7,NaN,Indiana,East,Central,62,123.3,122.0,1.3,102.2,120.6,...,1.20,15.6,-0.002,34,28,0.548,0.531,0.543,0.017,-2
8,NaN,Chicago,East,Central,61,111.7,113.1,-1.4,96.3,114.1,...,-1.39,12.2,-0.054,29,32,0.475,0.454,0.454,0.021,1
9,NaN,Atlanta,East,Southeast,60,120.4,122.7,-2.3,101.1,118.3,...,-3.33,13.1,-0.062,26,34,0.433,0.433,0.424,0.000,-2
10,NaN,Brooklyn,East,Atlantic,61,112.0,114.2,-2.2,97.5,114.3,...,-2.25,16.6,-0.010,24,37,0.393,0.447,0.428,-0.054,-1
11,NaN,Toronto,East,Atlantic,61,114.4,117.6,-3.2,99.3,114.4,...,-2.93,14.6,-0.025,23,38,0.377,0.411,0.395,-0.034,1
12,NaN,Charlotte,East,Southeast,61,107.6,118.0,-10.4,97.9,109.5,...,-9.66,14.2,-0.069,15,46,0.246,0.227,0.158,0.019,-4
13,NaN,Detroit,East,Central,60,112.1,121.0,-8.9,100.2,111.3,...,-7.80,11.2,0.005,9,51,0.150,0.213,0.207,-0.063,-2
14,NaN,Washington,East,Southeast,61,114.6,124.7,-10.1,103.3,110.7,...,-7.75,13.1,-0.065,9,52,0.148,0.229,0.167,-0.081,-15
15,NaN,Minnesota,West,Northwest,62,113.3,106.5,6.8,97.3,115.7,...,5.40,13.5,0.086,43,19,0.694,0.699,0.724,-0.005,1
16,NaN,Denver,West,Northwest,61,114.5,110.3,4.2,96.8,118.3,...,4.56,14.4,0.047,42,19,0.689,0.620,0.638,0.069,6
17,NaN,Oklahoma City,West,Northwest,61,120.9,113.3,7.6,99.9,120.2,...,7.17,16.5,0.017,42,19,0.689,0.675,0.750,0.014,-1
18,NaN,LA Clippers,West,Pacific,60,117.2,112.5,4.7,97.8,119.6,...,4.24,14.4,0.032,39,21,0.650,0.628,0.655,0.022,-1
19,NaN,New Orleans,West,Southwest,61,116.2,111.7,4.5,98.6,117.7,...,5.03,17.7,0.022,36,25,0.590,0.602,0.648,-0.012,1
20,NaN,Phoenix,West,Pacific,61,117.1,114.4,2.7,98.9,117.8,...,1.67,12.1,0.065,35,26,0.574,0.588,0.589,-0.014,-2
21,NaN,Sacramento,West,Pacific,60,118.1,117.8,0.3,99.6,117.4,...,0.49,15.4,-0.004,34,26,0.567,0.508,0.510,0.059,-1
22,NaN,Dallas,West,Southwest,61,118.7,118.0,0.7,100.3,118.3,...,0.87,17.4,-0.013,34,27,0.557,0.516,0.523,0.041,-2
23,NaN,LA Lakers,West,Pacific,63,117.1,117.4,-0.3,100.7,115.3,...,-0.49,15.5,0.018,34,29,0.540,0.490,0.490,0.050,1
24,NaN,Golden State,West,Pacific,60,118.6,117.2,1.4,99.7,117.7,...,1.11,13.8,0.042,32,28,0.533,0.537,0.546,-0.004,-1
25,NaN,Utah,West,Northwest,62,117.7,120.4,-2.7,100.1,116.6,...,-2.80,16.9,0.018,28,34,0.452,0.437,0.411,0.015,1
26,NaN,Houston,West,Southwest,60,112.8,113.0,-0.2,99.0,112.7,...,0.29,14.7,-0.010,26,34,0.433,0.495,0.493,-0.062,1
27,NaN,Memphis,West,Southwest,62,106.1,112.6,-6.5,98.2,107.3,...,-5.62,14.1,-0.058,21,41,0.339,0.319,0.286,0.020,1
28,NaN,Portland,West,Northwest,60,107.6,115.7,-8.1,97.5,109.0,...,-8.05,15.8,-0.081,17,43,0.283,0.301,0.233,-0.018,-1
29,NaN,San Antonio,West,Southwest,61,112.3,120.3,-8.0,101.5,110.3,...,-7.39,14.6,-0.038,13,48,0.213,0.297,0.237,-0.084,2

In [404]:
df2.isna().sum()

RANK        30
TEAM         0
CONF         0
DIVISION     0
GP           0
PPG          0
oPPG         0
pDIFF        0
PACE         0
oEFF         0
dEFF         0
eDIFF        0
SOS          0
rSOS         0
SAR          0
CONS         0
A4F          0
W            0
L            0
WIN%         0
eWIN%        0
pWIN%        0
ACH          0
STRK         0
dtype: int64

In [405]:
df2.drop('RANK', axis=1)

,TEAM,CONF,DIVISION,GP,PPG,oPPG,pDIFF,PACE,oEFF,dEFF,...,SAR,CONS,A4F,W,L,WIN%,eWIN%,pWIN%,ACH,STRK
0,Boston,East,Atlantic,60,121.3,109.9,11.4,98.0,122.8,111.2,...,11.18,16.6,0.096,48,12,0.800,0.758,0.875,0.042,11
1,Milwaukee,East,Central,62,121.4,116.9,4.5,100.7,119.9,115.5,...,3.29,15.6,0.059,41,21,0.661,0.611,0.648,0.050,6
2,Cleveland,East,Central,60,114.4,109.5,4.9,97.7,116.2,111.3,...,3.95,14.3,0.050,39,21,0.650,0.635,0.661,0.015,-1
3,New York,East,Atlantic,61,113.4,109.7,3.7,96.0,118.2,114.3,...,3.68,15.8,-0.003,36,25,0.590,0.597,0.622,-0.007,1
4,Philadelphia,East,Atlantic,60,117.1,113.8,3.3,98.4,118.6,115.2,...,1.70,17.1,-0.043,35,25,0.583,0.579,0.609,0.004,2
5,Orlando,East,Southeast,61,111.5,109.9,1.6,97.5,113.6,112.0,...,2.21,14.9,0.002,35,26,0.574,0.543,0.553,0.031,3
6,Miami,East,Southeast,60,110.6,109.9,0.7,96.8,114.2,113.4,...,0.42,13.1,-0.029,34,26,0.567,0.524,0.523,0.043,1
7,Indiana,East,Central,62,123.3,122.0,1.3,102.2,120.6,119.4,...,1.20,15.6,-0.002,34,28,0.548,0.531,0.543,0.017,-2
8,Chicago,East,Central,61,111.7,113.1,-1.4,96.3,114.1,115.5,...,-1.39,12.2,-0.054,29,32,0.475,0.454,0.454,0.021,1
9,Atlanta,East,Southeast,60,120.4,122.7,-2.3,101.1,118.3,120.5,...,-3.33,13.1,-0.062,26,34,0.433,0.433,0.424,0.000,-2
10,Brooklyn,East,Atlantic,61,112.0,114.2,-2.2,97.5,114.3,116.5,...,-2.25,16.6,-0.010,24,37,0.393,0.447,0.428,-0.054,-1
11,Toronto,East,Atlantic,61,114.4,117.6,-3.2,99.3,114.4,117.7,...,-2.93,14.6,-0.025,23,38,0.377,0.411,0.395,-0.034,1
12,Charlotte,East,Southeast,61,107.6,118.0,-10.4,97.9,109.5,120.1,...,-9.66,14.2,-0.069,15,46,0.246,0.227,0.158,0.019,-4
13,Detroit,East,Central,60,112.1,121.0,-8.9,100.2,111.3,120.2,...,-7.80,11.2,0.005,9,51,0.150,0.213,0.207,-0.063,-2
14,Washington,East,Southeast,61,114.6,124.7,-10.1,103.3,110.7,120.4,...,-7.75,13.1,-0.065,9,52,0.148,0.229,0.167,-0.081,-15
15,Minnesota,West,Northwest,62,113.3,106.5,6.8,97.3,115.7,108.7,...,5.40,13.5,0.086,43,19,0.694,0.699,0.724,-0.005,1
16,Denver,West,Northwest,61,114.5,110.3,4.2,96.8,118.3,113.9,...,4.56,14.4,0.047,42,19,0.689,0.620,0.638,0.069,6
17,Oklahoma City,West,Northwest,61,120.9,113.3,7.6,99.9,120.2,112.7,...,7.17,16.5,0.017,42,19,0.689,0.675,0.750,0.014,-1
18,LA Clippers,West,Pacific,60,117.2,112.5,4.7,97.8,119.6,114.9,...,4.24,14.4,0.032,39,21,0.650,0.628,0.655,0.022,-1
19,New Orleans,West,Southwest,61,116.2,111.7,4.5,98.6,117.7,113.1,...,5.03,17.7,0.022,36,25,0.590,0.602,0.648,-0.012,1
20,Phoenix,West,Pacific,61,117.1,114.4,2.7,98.9,117.8,115.1,...,1.67,12.1,0.065,35,26,0.574,0.588,0.589,-0.014,-2
21,Sacramento,West,Pacific,60,118.1,117.8,0.3,99.6,117.4,117.1,...,0.49,15.4,-0.004,34,26,0.567,0.508,0.510,0.059,-1
22,Dallas,West,Southwest,61,118.7,118.0,0.7,100.3,118.3,117.6,...,0.87,17.4,-0.013,34,27,0.557,0.516,0.523,0.041,-2
23,LA Lakers,West,Pacific,63,117.1,117.4,-0.3,100.7,115.3,115.7,...,-0.49,15.5,0.018,34,29,0.540,0.490,0.490,0.050,1
24,Golden State,West,Pacific,60,118.6,117.2,1.4,99.7,117.7,116.4,...,1.11,13.8,0.042,32,28,0.533,0.537,0.546,-0.004,-1
25,Utah,West,Northwest,62,117.7,120.4,-2.7,100.1,116.6,119.3,...,-2.80,16.9,0.018,28,34,0.452,0.437,0.411,0.015,1
26,Houston,West,Southwest,60,112.8,113.0,-0.2,99.0,112.7,112.9,...,0.29,14.7,-0.010,26,34,0.433,0.495,0.493,-0.062,1
27,Memphis,West,Southwest,62,106.1,112.6,-6.5,98.2,107.3,113.9,...,-5.62,14.1,-0.058,21,41,0.339,0.319,0.286,0.020,1
28,Portland,West,Northwest,60,107.6,115.7,-8.1,97.5,109.0,117.2,...,-8.05,15.8,-0.081,17,43,0.283,0.301,0.233,-0.018,-1
29,San Antonio,West,Southwest,61,112.3,120.3,-8.0,101.5,110.3,118.1,...,-7.39,14.6,-0.038,13,48,0.213,0.297,0.237,-0.084,2

In [406]:
df2 = df2.assign(RANK=range(len(df2)))
df2

,RANK,TEAM,CONF,DIVISION,GP,PPG,oPPG,pDIFF,PACE,oEFF,...,SAR,CONS,A4F,W,L,WIN%,eWIN%,pWIN%,ACH,STRK
0,0,Boston,East,Atlantic,60,121.3,109.9,11.4,98.0,122.8,...,11.18,16.6,0.096,48,12,0.800,0.758,0.875,0.042,11
1,1,Milwaukee,East,Central,62,121.4,116.9,4.5,100.7,119.9,...,3.29,15.6,0.059,41,21,0.661,0.611,0.648,0.050,6
2,2,Cleveland,East,Central,60,114.4,109.5,4.9,97.7,116.2,...,3.95,14.3,0.050,39,21,0.650,0.635,0.661,0.015,-1
3,3,New York,East,Atlantic,61,113.4,109.7,3.7,96.0,118.2,...,3.68,15.8,-0.003,36,25,0.590,0.597,0.622,-0.007,1
4,4,Philadelphia,East,Atlantic,60,117.1,113.8,3.3,98.4,118.6,...,1.70,17.1,-0.043,35,25,0.583,0.579,0.609,0.004,2
5,5,Orlando,East,Southeast,61,111.5,109.9,1.6,97.5,113.6,...,2.21,14.9,0.002,35,26,0.574,0.543,0.553,0.031,3
6,6,Miami,East,Southeast,60,110.6,109.9,0.7,96.8,114.2,...,0.42,13.1,-0.029,34,26,0.567,0.524,0.523,0.043,1
7,7,Indiana,East,Central,62,123.3,122.0,1.3,102.2,120.6,...,1.20,15.6,-0.002,34,28,0.548,0.531,0.543,0.017,-2
8,8,Chicago,East,Central,61,111.7,113.1,-1.4,96.3,114.1,...,-1.39,12.2,-0.054,29,32,0.475,0.454,0.454,0.021,1
9,9,Atlanta,East,Southeast,60,120.4,122.7,-2.3,101.1,118.3,...,-3.33,13.1,-0.062,26,34,0.433,0.433,0.424,0.000,-2
10,10,Brooklyn,East,Atlantic,61,112.0,114.2,-2.2,97.5,114.3,...,-2.25,16.6,-0.010,24,37,0.393,0.447,0.428,-0.054,-1
11,11,Toronto,East,Atlantic,61,114.4,117.6,-3.2,99.3,114.4,...,-2.93,14.6,-0.025,23,38,0.377,0.411,0.395,-0.034,1
12,12,Charlotte,East,Southeast,61,107.6,118.0,-10.4,97.9,109.5,...,-9.66,14.2,-0.069,15,46,0.246,0.227,0.158,0.019,-4
13,13,Detroit,East,Central,60,112.1,121.0,-8.9,100.2,111.3,...,-7.80,11.2,0.005,9,51,0.150,0.213,0.207,-0.063,-2
14,14,Washington,East,Southeast,61,114.6,124.7,-10.1,103.3,110.7,...,-7.75,13.1,-0.065,9,52,0.148,0.229,0.167,-0.081,-15
15,15,Minnesota,West,Northwest,62,113.3,106.5,6.8,97.3,115.7,...,5.40,13.5,0.086,43,19,0.694,0.699,0.724,-0.005,1
16,16,Denver,West,Northwest,61,114.5,110.3,4.2,96.8,118.3,...,4.56,14.4,0.047,42,19,0.689,0.620,0.638,0.069,6
17,17,Oklahoma City,West,Northwest,61,120.9,113.3,7.6,99.9,120.2,...,7.17,16.5,0.017,42,19,0.689,0.675,0.750,0.014,-1
18,18,LA Clippers,West,Pacific,60,117.2,112.5,4.7,97.8,119.6,...,4.24,14.4,0.032,39,21,0.650,0.628,0.655,0.022,-1
19,19,New Orleans,West,Southwest,61,116.2,111.7,4.5,98.6,117.7,...,5.03,17.7,0.022,36,25,0.590,0.602,0.648,-0.012,1
20,20,Phoenix,West,Pacific,61,117.1,114.4,2.7,98.9,117.8,...,1.67,12.1,0.065,35,26,0.574,0.588,0.589,-0.014,-2
21,21,Sacramento,West,Pacific,60,118.1,117.8,0.3,99.6,117.4,...,0.49,15.4,-0.004,34,26,0.567,0.508,0.510,0.059,-1
22,22,Dallas,West,Southwest,61,118.7,118.0,0.7,100.3,118.3,...,0.87,17.4,-0.013,34,27,0.557,0.516,0.523,0.041,-2
23,23,LA Lakers,West,Pacific,63,117.1,117.4,-0.3,100.7,115.3,...,-0.49,15.5,0.018,34,29,0.540,0.490,0.490,0.050,1
24,24,Golden State,West,Pacific,60,118.6,117.2,1.4,99.7,117.7,...,1.11,13.8,0.042,32,28,0.533,0.537,0.546,-0.004,-1
25,25,Utah,West,Northwest,62,117.7,120.4,-2.7,100.1,116.6,...,-2.80,16.9,0.018,28,34,0.452,0.437,0.411,0.015,1
26,26,Houston,West,Southwest,60,112.8,113.0,-0.2,99.0,112.7,...,0.29,14.7,-0.010,26,34,0.433,0.495,0.493,-0.062,1
27,27,Memphis,West,Southwest,62,106.1,112.6,-6.5,98.2,107.3,...,-5.62,14.1,-0.058,21,41,0.339,0.319,0.286,0.020,1
28,28,Portland,West,Northwest,60,107.6,115.7,-8.1,97.5,109.0,...,-8.05,15.8,-0.081,17,43,0.283,0.301,0.233,-0.018,-1
29,29,San Antonio,West,Southwest,61,112.3,120.3,-8.0,101.5,110.3,...,-7.39,14.6,-0.038,13,48,0.213,0.297,0.237,-0.084,2

In [407]:
filtered_df2 = df2[['RANK', 'TEAM', 'PPG', 'W', 'L']]
filtered_df2

    RANK           TEAM    PPG   W   L
0      0         Boston  121.3  48  12
1      1      Milwaukee  121.4  41  21
2      2      Cleveland  114.4  39  21
3      3       New York  113.4  36  25
4      4   Philadelphia  117.1  35  25
5      5        Orlando  111.5  35  26
6      6          Miami  110.6  34  26
7      7        Indiana  123.3  34  28
8      8        Chicago  111.7  29  32
9      9        Atlanta  120.4  26  34
10    10       Brooklyn  112.0  24  37
11    11        Toronto  114.4  23  38
12    12      Charlotte  107.6  15  46
13    13        Detroit  112.1   9  51
14    14     Washington  114.6   9  52
15    15      Minnesota  113.3  43  19
16    16         Denver  114.5  42  19
17    17  Oklahoma City  120.9  42  19
18    18    LA Clippers  117.2  39  21
19    19    New Orleans  116.2  36  25
20    20        Phoenix  117.1  35  26
21    21     Sacramento  118.1  34  26
22    22         Dallas  118.7  34  27
23    23      LA Lakers  117.1  34  29
24    24   Golden State  118.6  32  28
25    25           Utah  117.7  28  34
26    26        Houston  112.8  26  34
27    27        Memphis  106.1  21  41
28    28       Portland  107.6  17  43
29    29    San Antonio  112.3  13  48

In [408]:
team_ppg = filtered_df.groupby('TEAM')['PPG'].sum().reset_index()
team_ppg.columns = ['TEAM', 'Total_PPG']

wins = filtered_df2[['TEAM', 'W']]

In [409]:
import altair as alt

combined_df = pd.concat([team_ppg, wins], axis=1)

chart = alt.Chart(combined_df).mark_circle(size=60).encode(
    x=alt.X('Total_PPG:Q', title='Total Points Per Game (PPG)'),
    y=alt.Y('W:Q', title='Number of Wins'),
    tooltip=['TEAM:N'] 
).properties(
    title='Comparison of Total PPG and Number of Wins for Each Team'
).interactive()

chart

/Users/nayakhayat/opt/anaconda3/lib/python3.9/site-packages/altair/utils/data.py:230: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  return {"values": data.to_dict(orient="records")}

alt.Chart(...)

In [410]:
excel_file_path = 'facebook_nbadata.xlsx'
facebookdf = pd.read_excel(excel_file_path)

csv_file_path = 'facebook_nbadata.csv'
facebookdf.to_csv(csv_file_path, index=False)

In [411]:
facebookdf = pd.read_csv('facebook_nbadata.csv')
facebookdf

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"NBA: number of Facebook fans 2023, by team",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Number of Facebook likes for National Basketba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,October 2023,October 2022,March 2022,September 2021,March 2021,July 2020,June 2020,September 2019,...,"March 28, 2017","September 22, 2016","March 15, 2016","September 14, 2015","March 16, 2015","September 11, 2014","March 10, 2014","September 6, 2013","February 28, 2013","September 04, 2012"
4,NaN,NBA,39.93,39.41,39.13,39.17,39,38.54,38.49,38.05,...,32.77,31.34,29.16,27.36,27.4,25.68,20.38,17.85,15.94,14.47
5,NaN,Los Angeles Lakers,21.87,21.6,21.73,21.8,21.75,21.9,21.9,21.57,...,21.86,21.85,21.46,21.25,22.34,21.07,18.82,16.66,16.11,14.66
6,NaN,Chicago Bulls,16.69,16.78,16.79,17,17.24,17.42,17.48,17.74,...,18.93,18.76,18.25,17.93,18.04,16,12.68,9.06,8.3,6.98
7,NaN,Houston Rockets,15.86,15.83,15.68,15.61,15.42,14.84,14.7,12.56,...,3.82,3.81,3.55,3.28,2.85,2.47,1.63,0.75,0.65,0.57
8,NaN,Miami Heat,14.3,14.36,14.5,14.63,14.85,14.96,15.02,15.27,...,16.06,16.21,16.12,16.05,16.44,15.58,10.98,8.6,7.68,6.77
9,NaN,Golden State Warriors,12,11.68,11.46,11.52,11.59,11.6,11.63,11.72,...,10.52,9.15,6.41,4.49,2.78,2.43,1.47,0.52,0.4,0.36
10,NaN,Boston Celtics,8.67,8.65,8.63,8.7,8.81,8.88,8.91,9.01,...,8.77,8.78,8.64,8.57,8.77,8.54,7.91,7,6.89,6.77
11,NaN,Cleveland Cavaliers,7.83,7.92,8.03,8.14,8.26,8.37,8.41,8.59,...,8.36,7.15,4.98,4.32,3.4,2.16,1.44,1.01,0.94,0.9
12,NaN,Sacramento Kings,7.33,7.4,7.49,7.59,7.69,7.83,7.88,7.51,...,1.76,1.75,1.61,1.36,1.19,0.96,0.72,0.28,0.24,0.22
13,NaN,San Antonio Spurs,6.62,6.65,6.71,6.78,6.86,6.93,6.96,7.05,...,7.16,6.95,6.46,5.97,5.58,5.03,2.84,1.82,1.47,1.35
14,NaN,Oklahoma City Thunder,6.28,6.4,6.54,6.68,6.8,6.91,6.94,7.07,...,7.56,6.69,5.9,5.59,5.55,5.02,3.5,2.12,1.89,1.52
15,NaN,New York Knicks,5.51,5.51,5.56,5.6,5.67,5.72,5.74,5.83,...,6.12,6.1,5.83,5.66,5.55,5.37,4.54,3.82,3.5,2.88
16,NaN,Washington Wizards,4.95,5.01,5.13,5.21,4.87,4.77,4.81,1.55,...,1.53,1.52,1.32,1.2,1.02,0.73,0.4,0.21,0.18,0.16
17,NaN,Dallas Mavericks,4.37,4.23,4.29,4.32,4.35,4.35,4.36,4.37,...,4.52,4.52,4.42,4.3,4.08,3.77,3.01,2.6,2.5,2.31
18,NaN,Los Angeles Clippers,3.7,3.71,3.74,3.78,3.79,3.78,3.79,3.78,...,3.85,3.84,3.62,3.35,3.06,2.73,1.97,0.84,0.67,0.52
19,NaN,Utah Jazz,3.1,2.85,2.67,2.12,1.81,1.81,1.82,1.81,...,1.17,1.16,1.11,1.02,0.93,0.82,0.69,0.41,0.37,0.35
20,NaN,Indiana Pacers,3.08,3.08,3.1,3.13,3.16,3.18,3.2,3.25,...,3.32,3.31,3.19,3.02,2.87,2.52,1.44,0.35,0.22,0.2
21,NaN,Brooklyn Nets,2.91,2.89,2.89,2.87,2.8,2.72,2.73,2.7,...,2.8,2.79,2.7,2.62,2.52,2.23,1.64,1.14,0.82,0.37
22,NaN,Orlando Magic,2.64,2.61,2.63,2.65,2.68,2.7,2.71,2.75,...,2.76,2.76,2.71,2.63,2.57,2.47,2.27,1.84,1.73,1.56
23,NaN,Toronto Raptors,2.58,2.58,2.6,2.62,2.65,2.65,2.66,2.68,...,2.18,2.16,1.92,1.74,1.56,1.23,0.66,0.42,0.39,0.36
24,NaN,Portland Trailblazers,2.46,2.45,2.44,2.41,2.43,2.43,2.44,2.46,...,2.4,2.39,2.25,2.1,1.94,1.67,1.11,0.47,0.43,0.4
25,NaN,Milwaukee Bucks,2.16,2.11,2.1,2.09,1.93,1.91,1.91,1.82,...,1.42,1.41,1.26,1.1,0.96,0.78,0.62,0.29,0.25,0.23
26,NaN,Denver Nuggets,2.12,2.02,2.03,2.04,2.04,1.99,1.99,2.01,...,1.96,1.96,1.91,1.83,1.83,1.67,1.48,1.03,0.93,0.86
27,NaN,Phoenix Suns,2,1.93,1.93,1.92,1.86,1.86,1.87,1.88,...,1.89,1.89,1.85,1.78,1.75,1.54,1.3,0.8,0.75,0.73
28,NaN,Detroit Pistons,1.93,1.95,1.97,2,2.02,2.04,2.04,1.79,...,1.86,1.85,1.64,1.48,1.37,1.21,0.95,0.52,0.47,0.45
29,NaN,Memphis Grizzlies,1.89,1.84,1.8,1.78,1.79,1.79,1.79,1.8,...,1.81,1.81,1.74,1.61,1.43,1.17,0.87,0.29,0.21,0.18
30,NaN,Philadelphia 76ers,1.81,1.77,1.75,1.74,1.74,1.75,1.75,1.75,...,1.53,1.52,1.39,1.29,1.2,1,0.78,0.36,0.31,0.29
31,NaN,Minnesota Timberwolves,1.79,1.79,1.8,1.82,1.84,1.85,1.86,1.89,...,1.84,1.83,1.65,1.53,1.36,1.12,0.84,0.33,0.27,0.23
32,NaN,New Orleans Pelicans,1.75,1.73,1.74,1.75,1.76,1.76,1.76,1.75,...,1.64,1.63,1.55,1.4,1.23,0.96,0.76,0.35,0.31,0.27
33,NaN,Charlotte Hornets,1.72,1.71,1.71,1.71,1.72,1.71,1.71,1.74,...,1.74,1.73,1.62,1.42,1.25,0.93,0.6,0.2,0.16,0.13
34,NaN,Atlanta Hawks,1.57,1.57,1.58,1.59,1.57,1.59,1.59,1.61,...,1.6,1.59,1.51,1.38,1.2,0.96,0.76,0.36,0.3,0.27

In [412]:
facebookdf = pd.read_csv('facebook_nbadata.csv', skiprows=3)

facebookdf.columns = facebookdf.iloc[0]

facebookdf = facebookdf.drop(0)

facebookdf = facebookdf.reset_index(drop=True)

In [413]:
facebookdf.drop(columns=facebookdf.columns[0], inplace=True)

facebookdf.rename(columns={facebookdf.columns[0]: "TEAM"}, inplace=True)

In [414]:
fblikes = facebookdf[['TEAM','October 2023']]
fblikes = fblikes.iloc[1:]
fblikes

0                     TEAM October 2023
1       Los Angeles Lakers        21.87
2            Chicago Bulls        16.69
3          Houston Rockets        15.86
4               Miami Heat         14.3
5    Golden State Warriors           12
6           Boston Celtics         8.67
7      Cleveland Cavaliers         7.83
8         Sacramento Kings         7.33
9        San Antonio Spurs         6.62
10   Oklahoma City Thunder         6.28
11         New York Knicks         5.51
12      Washington Wizards         4.95
13        Dallas Mavericks         4.37
14    Los Angeles Clippers          3.7
15               Utah Jazz          3.1
16          Indiana Pacers         3.08
17           Brooklyn Nets         2.91
18           Orlando Magic         2.64
19         Toronto Raptors         2.58
20   Portland Trailblazers         2.46
21         Milwaukee Bucks         2.16
22          Denver Nuggets         2.12
23            Phoenix Suns            2
24         Detroit Pistons         1.93
25       Memphis Grizzlies         1.89
26      Philadelphia 76ers         1.81
27  Minnesota Timberwolves         1.79
28    New Orleans Pelicans         1.75
29       Charlotte Hornets         1.72
30           Atlanta Hawks         1.57

In [415]:
wins

             TEAM   W
0          Boston  48
1       Milwaukee  41
2       Cleveland  39
3        New York  36
4    Philadelphia  35
5         Orlando  35
6           Miami  34
7         Indiana  34
8         Chicago  29
9         Atlanta  26
10       Brooklyn  24
11        Toronto  23
12      Charlotte  15
13        Detroit   9
14     Washington   9
15      Minnesota  43
16         Denver  42
17  Oklahoma City  42
18    LA Clippers  39
19    New Orleans  36
20        Phoenix  35
21     Sacramento  34
22         Dallas  34
23      LA Lakers  34
24   Golden State  32
25           Utah  28
26        Houston  26
27        Memphis  21
28       Portland  17
29    San Antonio  13

In [416]:
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Los Angeles Clippers', 'LA Clippers')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Los Angeles Lakers', 'LA Lakers')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Boston Celtics', 'Boston')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Chicago Bulls', 'Chicago')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Houston Rockets', 'Houston')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Miami Heat', 'Miami')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Golden State Warriors', 'Golden State')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Cleveland Cavaliers', 'Cleveland')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Sacramento Kings', 'Sacramento')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('San Antonio Spurs', 'San Antonio')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Oklahoma City Thunder', 'Oklahoma City')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('New York Knicks', 'New York')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Washington Wizards', 'Washington')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Utah Jazz', 'Utah')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Dallas Mavericks', 'Dallas')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Indiana Pacers', 'Indiana')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Brooklyn Nets', 'Brooklyn')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Los Angeles Clippers', 'LA Clippers')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Orlando Magic', 'Orlando')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Toronto Raptors', 'Toronto')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Portland Trailblazers', 'Portland')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Milwaukee Bucks', 'Milwaukee')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Denver Nuggets', 'Denver')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Phoenix Suns', 'Phoenix')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Detroit Pistons', 'Detroit')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Memphis Grizzlies', 'Memphis')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Philadelphia 76ers', 'Philadelphia')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Minnesota Timberwolves', 'Minnesota')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('New Orleans Pelicans', 'New Orleans')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Charlotte Hornets', 'Charlotte')
fblikes['TEAM'] = fblikes['TEAM'].str.replace('Atlanta Hawks', 'Atlanta')

print(fblikes)

0            TEAM October 2023
1       LA Lakers        21.87
2         Chicago        16.69
3         Houston        15.86
4           Miami         14.3
5    Golden State           12
6          Boston         8.67
7       Cleveland         7.83
8      Sacramento         7.33
9     San Antonio         6.62
10  Oklahoma City         6.28
11       New York         5.51
12     Washington         4.95
13         Dallas         4.37
14    LA Clippers          3.7
15           Utah          3.1
16        Indiana         3.08
17       Brooklyn         2.91
18        Orlando         2.64
19        Toronto         2.58
20       Portland         2.46
21      Milwaukee         2.16
22         Denver         2.12
23        Phoenix            2
24        Detroit         1.93
25        Memphis         1.89
26   Philadelphia         1.81
27      Minnesota         1.79
28    New Orleans         1.75
29      Charlotte         1.72
30        Atlanta         1.57

In [417]:
combined_df = fblikes.merge(wins, how = 'inner', on = ['TEAM'])
combined_df

             TEAM October 2023   W
0       LA Lakers        21.87  34
1         Chicago        16.69  29
2         Houston        15.86  26
3           Miami         14.3  34
4    Golden State           12  32
5          Boston         8.67  48
6       Cleveland         7.83  39
7      Sacramento         7.33  34
8     San Antonio         6.62  13
9   Oklahoma City         6.28  42
10       New York         5.51  36
11     Washington         4.95   9
12         Dallas         4.37  34
13    LA Clippers          3.7  39
14           Utah          3.1  28
15        Indiana         3.08  34
16       Brooklyn         2.91  24
17        Orlando         2.64  35
18        Toronto         2.58  23
19       Portland         2.46  17
20      Milwaukee         2.16  41
21         Denver         2.12  42
22        Phoenix            2  35
23        Detroit         1.93   9
24        Memphis         1.89  21
25   Philadelphia         1.81  35
26      Minnesota         1.79  43
27    New Orleans         1.75  36
28      Charlotte         1.72  15
29        Atlanta         1.57  26

In [418]:
combined_df.columns = ['TEAM', 'Oct 2023 Likes', 'W']
combined_df

             TEAM Oct 2023 Likes   W
0       LA Lakers          21.87  34
1         Chicago          16.69  29
2         Houston          15.86  26
3           Miami           14.3  34
4    Golden State             12  32
5          Boston           8.67  48
6       Cleveland           7.83  39
7      Sacramento           7.33  34
8     San Antonio           6.62  13
9   Oklahoma City           6.28  42
10       New York           5.51  36
11     Washington           4.95   9
12         Dallas           4.37  34
13    LA Clippers            3.7  39
14           Utah            3.1  28
15        Indiana           3.08  34
16       Brooklyn           2.91  24
17        Orlando           2.64  35
18        Toronto           2.58  23
19       Portland           2.46  17
20      Milwaukee           2.16  41
21         Denver           2.12  42
22        Phoenix              2  35
23        Detroit           1.93   9
24        Memphis           1.89  21
25   Philadelphia           1.81  35
26      Minnesota           1.79  43
27    New Orleans           1.75  36
28      Charlotte           1.72  15
29        Atlanta           1.57  26

In [419]:
import altair as alt

chart = alt.Chart(combined_df).mark_circle(size=60).encode(
    x=alt.X('Oct 2023 Likes:Q', title='Facebook Likes (Oct 2023)'),
    y=alt.Y('W:Q', title='Number of Wins'),
    tooltip=['TEAM:N']  
).properties(
    title='Comparison of Facebook Likes and Number of Wins for Each Team'
).interactive()

chart

alt.Chart(...)